import { Box } from "@mui/material";
import React from "react";
import { Helmet } from "react-helmet";
import { NavBar, SideBar, SideBarWithoutText, MobileBottom } from "../../components/Common";
import { COMPANY_ADMIN_SIDEBAR_LINKS } from "../../constants/Company-admin-sidebar";
import { CompanyAdminProtectRoute } from "../../protectRoutes";


/**
 * Home Page of the Application
 * @return {JSX.Element}
 */

export default function Schedules() {
    return (
        <CompanyAdminProtectRoute>
                <Helmet>
                    <title>Portal</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                    {/* <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" /> */}
                </Helmet>
                <Box color={"text.primary"} className="bg-gray-200 min-h-[100vh]">
                    <NavBar type={'company-admin'} />
                    <div className="border">
                        <div className="flex justify-around">
                            <div className="sm:w-2/12 mt-12">
                                <div className="hidden md:block">
                                    <SideBar links={COMPANY_ADMIN_SIDEBAR_LINKS} href={'/company-admin/schedules'} />
                                </div>
                                <div className="ml-6 md:hidden">
                                    <SideBarWithoutText links={COMPANY_ADMIN_SIDEBAR_LINKS} href={'/company-admin/schedules'} />
                                </div>
                            </div>
                            <div className="md:w-9/12 sm:w-9/12 w-11/12 mt-32 mr-5 lg:ml-16 bg-white shadow-md rounded-md">
                                <Schedules />
                            </div>
                        </div>
                    </div>
                    <div className="sm:hidden">
                        <MobileBottom />
                    </div>
                </Box>
        </CompanyAdminProtectRoute>
    );
}